/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package uasprak;

import javax.swing.text.Position;

/**
 *
 * @author REPUBLIC OF GAMERS
 */
public class Layer1 extends javax.swing.JFrame {

    /**
     * Creates new form Layer1
     */
    public Layer1() {
        initComponents();
        setLocation(300, 130);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bgplayer1 = new javax.swing.JPanel();
        btpembelilayer2 = new javax.swing.JButton();
        btadminlayer1 = new javax.swing.JButton();
        btpembelilayer1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        bgplayer1.setBackground(new java.awt.Color(255, 153, 0));
        bgplayer1.setPreferredSize(new java.awt.Dimension(205, 163));
        bgplayer1.setLayout(null);

        btpembelilayer2.setBackground(new java.awt.Color(204, 153, 0));
        btpembelilayer2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btpembelilayer2.setForeground(new java.awt.Color(255, 255, 255));
        btpembelilayer2.setText("DISKON");
        btpembelilayer2.setBorder(null);
        btpembelilayer2.setBorderPainted(false);
        btpembelilayer2.setContentAreaFilled(false);
        btpembelilayer2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btpembelilayer2.setDefaultCapable(false);
        btpembelilayer2.setFocusPainted(false);
        btpembelilayer2.setFocusable(false);
        btpembelilayer2.setPreferredSize(new java.awt.Dimension(172, 21));
        btpembelilayer2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpembelilayer2ActionPerformed(evt);
            }
        });
        bgplayer1.add(btpembelilayer2);
        btpembelilayer2.setBounds(0, 280, 280, 54);

        btadminlayer1.setBackground(new java.awt.Color(204, 153, 0));
        btadminlayer1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btadminlayer1.setForeground(new java.awt.Color(255, 255, 255));
        btadminlayer1.setText("ADMIIN");
        btadminlayer1.setBorder(null);
        btadminlayer1.setBorderPainted(false);
        btadminlayer1.setContentAreaFilled(false);
        btadminlayer1.setDisplayedMnemonicIndex(0);
        btadminlayer1.setFocusPainted(false);
        btadminlayer1.setFocusable(false);
        btadminlayer1.setPreferredSize(new java.awt.Dimension(172, 21));
        btadminlayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btadminlayer1ActionPerformed(evt);
            }
        });
        bgplayer1.add(btadminlayer1);
        btadminlayer1.setBounds(0, 159, 280, 54);

        btpembelilayer1.setBackground(new java.awt.Color(204, 153, 0));
        btpembelilayer1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btpembelilayer1.setForeground(new java.awt.Color(255, 255, 255));
        btpembelilayer1.setText("PEMBELI");
        btpembelilayer1.setBorder(null);
        btpembelilayer1.setBorderPainted(false);
        btpembelilayer1.setContentAreaFilled(false);
        btpembelilayer1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btpembelilayer1.setDefaultCapable(false);
        btpembelilayer1.setDisplayedMnemonicIndex(0);
        btpembelilayer1.setFocusPainted(false);
        btpembelilayer1.setFocusable(false);
        btpembelilayer1.setPreferredSize(new java.awt.Dimension(172, 21));
        btpembelilayer1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpembelilayer1ActionPerformed(evt);
            }
        });
        bgplayer1.add(btpembelilayer1);
        btpembelilayer1.setBounds(0, 219, 280, 54);

        jLabel2.setBackground(new java.awt.Color(255, 204, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HUNGRY HEROES");
        bgplayer1.add(jLabel2);
        jLabel2.setBounds(0, 50, 270, 50);

        jPanel2.setBackground(new java.awt.Color(255, 102, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 280, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        bgplayer1.add(jPanel2);
        jPanel2.setBounds(0, 40, 280, 70);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/uasprak/icon/WhatsApp Image 2022-05-19 at 11.33.03.jpeg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(bgplayer1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 728, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgplayer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btadminlayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btadminlayer1ActionPerformed
        layer2 pindah1 = new layer2();
        pindah1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btadminlayer1ActionPerformed

    private void btpembelilayer1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpembelilayer1ActionPerformed
        layer4 pindah3 = new layer4();
        pindah3.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btpembelilayer1ActionPerformed

    private void btpembelilayer2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpembelilayer2ActionPerformed
        layer5 pindah4 = new layer5();
        pindah4.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btpembelilayer2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Layer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Layer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Layer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Layer1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Layer1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bgplayer1;
    private javax.swing.JButton btadminlayer1;
    private javax.swing.JButton btpembelilayer1;
    private javax.swing.JButton btpembelilayer2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
